### ISSUE TITLE
New release for byteorder dependency

### ISSUE THREAD

**Issue by flub** [luser/rust-test-assembler#10]
Hi!  It would be great if a new release could be published for the byteorder dependency bump that already happened.  This crate is the only reason we get a duplicate byteorder in our dependencies.

thanks!

**Comment by luser** [comment]
Oh, sure, I can do that! Thanks for the info!

**Comment by luser** [comment]
I just released [0.1.6](https://crates.io/crates/test-assembler/0.1.6). Hope that helps!

**Comment by flub** [comment]
thanks!
