### ISSUE TITLE
Label::offset seems broken

### ISSUE THREAD

**Issue by fitzgen** [luser/rust-test-assembler#2]
This is producing `None` instead of `Some(0)`.

``` rust
    #[test]
    fn test_simple_labels() {
        let start = Label::new();
        let end = Label::new();

        let section = Section::new()
            .mark(&start)
            .mark(&end);

        assert_eq!(start.offset(&end), Some(0));
    }
```

cc @JimBlandy

**Comment by luser** [comment]
I can reproduce this locally.

**Comment by luser** [comment]
Okay, I think I understand the bug, but I haven't touched this code in a while so I'm finding it hard to reason about a fix. Essentially:
`Section::mark` sets the passed-in `Label` to reference a _new_ label (which is set as `Section::start_ + length`). This means that after the two calls to mark you have something like:
start -> L1 -> section.start_
end -> L2 -> section.start_

Calling `start.offset(&end)` will traverse the chain start -> L1 -> section.start_, but none of those is equivalent to end so it can't figure out that they're related. The original C++ implementation of `Label::Binding::Set` dereferences bindings to point at their root value:
https://chromium.googlesource.com/breakpad/breakpad/+/master/src/common/test_assembler.cc#148

...so it avoids this issue.

**Comment by luser** [comment]
I sorted it out. Thanks for the bug report! I'll push 0.1.3 to crates.io shortly.
